### ISSUE TITLE
Error loading page with plugin

### ISSUE THREAD

**Issue by arc64** [ether/ep_comments#126]
Issue with loading page with plugin, error message below

---

An error occurred
The error was reported with the following id: 'rBzQdXrzvLAxvAvFV4jp'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: rBzQdXrzvLAxvAvFV4jp
URL: https://video.etherpad.com/p/standup_test3
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Uncaught TypeError: Cannot read property 'length' of undefined in https://video.etherpad.com/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=f9939ec6 at line 22'

**Comment by JohnMcLear** [comment]
Tests are all passing.  Expect browser cache issue.  Please try from another browser or hit control f5.

**Comment by JohnMcLear** [comment]
Oh wait this is video.etherpad.com...

**Comment by JohnMcLear** [comment]
Pad is loading fine for me...

**Comment by JohnMcLear** [comment]
i spent a few hours and found htis

```
May 28 20:23:42 JohnEtherpad run.sh[27763]: [2020-05-28 20:23:42.956] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
May 28 20:23:42 JohnEtherpad run.sh[27763]: [2020-05-28 20:23:42.957] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
May 28 20:25:02 JohnEtherpad run.sh[27763]: [2020-05-28 20:25:02.058] [ERROR] console - Error compressing JS (../../node_modules/ep_comments_page/static/tests/frontend/specs/commentCopyPaste.js) using UglifyJS { SyntaxError: Unexpected token: punc «(»
May 28 20:25:02 JohnEtherpad run.sh[27763]: at JS_Parse_Error.get (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at formatError (internal/util/inspect.js:818:16)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at formatRaw (internal/util/inspect.js:617:14)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at formatValue (internal/util/inspect.js:509:10)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at inspect (internal/util/inspect.js:189:10)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at formatWithOptions (util.js:84:12)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at Object.format (util.js:72:10)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at Object.inspect (/home/etherpad/etherpad-lite/src/node_modules/log4js/lib/layouts.js:31:50)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at Object.deprecated (internal/util.js:66:15)
May 28 20:25:02 JohnEtherpad run.sh[27763]: at formatValue (internal/util/inspect.js:491:31)
May 28 20:25:02 JohnEtherpad run.sh[27763]: message: 'Unexpected token: punc «(»',
May 28 20:25:02 JohnEtherpad run.sh[27763]: filename: '0',
May 28 20:25:02 JohnEtherpad run.sh[27763]: line: 385,
May 28 20:25:02 JohnEtherpad run.sh[27763]: col: 45,
May 28 20:25:02 JohnEtherpad run.sh[27763]: pos: 14081 }
May 28 20:25:02 JohnEtherpad run.sh[27763]: SyntaxError: Unexpected token: punc «(»
```

It's the closest thing I have to a failure case..

For now I will remove the plugin and see if problem persists..
